options(stringsAsFactors=FALSE)
.libPaths(c("C:/Users/32266/AppData/Local/R/win-library/4.5","G:/gurobi/Rlib45",.libPaths()))
library(ggplot2)
dir.create("panels",showWarnings=FALSE)
save_panel <- function(p,n,w=5.2,h=4.4){ggsave(file.path("panels",paste0(n,".pdf")),p,width=w,height=h,device=cairo_pdf,bg="white");ggsave(file.path("panels",paste0(n,".png")),p,width=w,height=h,dpi=300,bg="white")}
th <- function(s=12) theme_classic(base_size=s)+theme(plot.title=element_text(face="bold",hjust=.5,size=rel(1.02)),plot.subtitle=element_text(hjust=.5,size=rel(.78)),axis.text=element_text(color="black"),legend.title=element_blank(),plot.margin=margin(8,9,8,9))
disp <- function(x) ifelse(x=="LASSO","Elastic net",x)
z<-read.csv("eight_models_sample_predictions.csv");z<-z[z$Split=="Screening holdout",];z$Model<-disp(z$Model)
lev<-c("RF","SVM","GLM","GBM","KNN","NNET","Elastic net","DT")
z$Model<-factor(z$Model,levels=lev)
cols<-setNames(c("#E58043","#459B71","#A464B2","#D95765","#6F85C1","#C5A03B","#3188AD","#7C7168"),lev)
pA<-ggplot(z,aes(Model,AbsResidual,fill=Model))+geom_boxplot(width=.62,outlier.size=1.2)+scale_fill_manual(values=cols,guide="none")+coord_flip()+labs(title="Absolute prediction residuals",subtitle="41 candidates | same screening holdout (n = 50)",x=NULL,y="Absolute residual |observed - predicted|")+th()
save_panel(pA,"FigureS2_A_residual_boxplots")
ec<-do.call(rbind,lapply(split(z,z$Model),function(d){xx<-sort(unique(c(0,d$AbsResidual,1)));data.frame(Model=as.character(d$Model[1]),x=xx,y=vapply(xx,function(t)mean(d$AbsResidual>t),numeric(1)))}))
pB<-ggplot(ec,aes(x,y,color=Model))+geom_step(linewidth=.8)+scale_color_manual(values=cols)+scale_y_continuous(limits=c(0,1))+labs(title="Reverse cumulative residuals",subtitle="41 candidates | same screening holdout (n = 50)",x="Absolute residual threshold",y="Proportion with residual > threshold")+th()+theme(legend.position="bottom",legend.text=element_text(size=8))+guides(color=guide_legend(nrow=2))
save_panel(pB,"FigureS2_B_residual_reverse_ECDF")
rd<-do.call(rbind,lapply(split(z,z$Model),function(d){r<-pROC::roc(d$Y,d$Probability,levels=c(0,1),direction="<",quiet=TRUE);data.frame(Model=as.character(d$Model[1]),FPR=1-r$specificities,TPR=r$sensitivities)}))
me<-read.csv("eight_models_metrics.csv");me<-me[me$Split=="Screening holdout",];me$Model<-disp(me$Model)
labs_auc<-setNames(sprintf("%s  %.3f",me$Model,me$AUC),me$Model)
pC<-ggplot(rd,aes(FPR,TPR,color=Model))+geom_abline(slope=1,intercept=0,color="grey75",linetype=2)+geom_path(linewidth=.8)+scale_color_manual(values=cols,labels=labs_auc)+coord_equal(xlim=c(0,1),ylim=c(0,1))+labs(title="Eight-algorithm ROC curves",subtitle="Screening holdout; reused for feature ranking",x="False-positive rate",y="True-positive rate")+th()+theme(legend.position="bottom",legend.text=element_text(size=8))+guides(color=guide_legend(nrow=4))
pC<-pC+theme(legend.position="inside",legend.position.inside=c(.7,.24),legend.background=element_rect(fill="white",color=NA),legend.key.height=grid::unit(.25,"cm"),legend.text=element_text(size=8))+guides(color=guide_legend(nrow=4))
save_panel(pC,"FigureS2_C_screening_ROC",5.2,4.4)
im<-read.csv("eight_models_importance_rankings.csv");im<-im[im$variable %in% c("AGT","CXCR4","FOS","EPHX2"),];im$Model<-factor(disp(im$Model),levels=lev);im$variable<-factor(im$variable,levels=rev(c("AGT","CXCR4","FOS","EPHX2")))
pD<-ggplot(im,aes(Model,variable,fill=Rank))+geom_tile(color="white",linewidth=.8)+geom_text(aes(label=Rank),size=3.5)+scale_fill_gradient(low="#A8DBCC",high="#FFF2DD",limits=c(1,41),breaks=c(1,20,41))+labs(title="Candidate-gene ranking sensitivity",subtitle="Permutation RMSE rankings among 41 genes\nFinal model: AGT + CXCR4 + FOS; EPHX2 shown for comparison",x=NULL,y=NULL)+th(11)+theme(axis.text.x=element_text(angle=45,hjust=1),axis.line=element_blank(),axis.ticks=element_blank(),legend.position="bottom",legend.title=element_text(size=10))+guides(fill=guide_colorbar(title="Rank"))
save_panel(pD,"FigureS2_D_candidate_rankings",5.8,4.2)
m<-as.matrix(read.csv("WGCNA_correlations_recovered.csv",row.names=1,check.names=FALSE))
heat<-expand.grid(Gene=rownames(m),Module=colnames(m));heat$r<-as.vector(m)
heat$Gene<-factor(heat$Gene,levels=rev(rownames(m)));heat$Module<-factor(heat$Module,levels=colnames(m))
pF<-ggplot(heat,aes(Module,Gene,fill=r))+geom_tile(color="white",linewidth=.5)+geom_text(aes(label=sprintf("%.2f",r)),size=3.5)+scale_fill_gradient2(low="#387BB3",mid="#FFF7DB",high="#D85A52",limits=c(-1,1),name="Pearson r")+labs(title="Gene-module eigengene correlations",subtitle="Recovered from original WGCNA matrix (171 samples)\nAGT was not included in the 5,000-gene WGCNA input",x=NULL,y=NULL)+th(11)+theme(axis.text.x=element_text(angle=45,hjust=1),axis.line=element_blank(),axis.ticks=element_blank(),legend.position="bottom")
save_panel(pF,"FigureS2_F_WGCNA_correlations",5.8,4.0)
write.csv(heat,"WGCNA_correlations_plot_data.csv",row.names=FALSE)
