suppressPackageStartupMessages({library(Seurat);library(dplyr);library(limma)})
p <- "G:/1Yunvjian/0a26.7.7singlecell/8.10/fibroblast_revision_final/results/objects/fibroblast_revision_final_no_unassigned.rds"
x <- readRDS(p); DefaultAssay(x) <- "RNA"; x[["RNA"]] <- JoinLayers(x[["RNA"]])
genes <- intersect(c("POSTN","TNC","COL11A1","SERPINE1","FAP"), rownames(x))
set.seed(12345)
x <- AddModuleScore(x, features=list(genes), name="score_Activated_five_gene", assay="RNA", seed=12345)
x <- AddModuleScore(x, features=list(c("CD68","TRAC","KRT5","RGS5")), name="score_Contamination_four_gene", assay="RNA", seed=12345)
m <- x[[]] %>% group_by(sample,group,dataset,cohort) %>% summarise(total_fibro=n(), score=mean(score_Activated_five_gene1),.groups="drop") %>% filter(total_fibro>=50)
m$group <- factor(m$group,levels=c("NC","PD")); m$dataset <- factor(m$dataset)
design <- model.matrix(~dataset+group,m)
fit <- eBayes(lmFit(t(as.matrix(m$score)),design),robust=TRUE,trend=TRUE)
tt <- topTable(fit,coef="groupPD",number=Inf,sort.by="none")
print(genes); print(tt); write.csv(m,"G:/1Yunvjian/FigureS4_fibroblast_dataset_bias/five_gene_activated_sample_scores.csv",row.names=FALSE)
write.csv(tt,"G:/1Yunvjian/FigureS4_fibroblast_dataset_bias/five_gene_activated_model.csv",row.names=FALSE)
m164 <- m %>% filter(dataset=="GSE164241") %>% mutate(cohort=factor(cohort))
design164 <- model.matrix(~cohort+group,m164)
fit164 <- eBayes(lmFit(t(as.matrix(m164$score)),design164),robust=TRUE,trend=TRUE)
tt164 <- topTable(fit164,coef="groupPD",number=Inf,sort.by="none")
print(tt164); write.csv(tt164,"G:/1Yunvjian/FigureS4_fibroblast_dataset_bias/five_gene_activated_GSE164241_model.csv",row.names=FALSE)
mc <- x[[]] %>% group_by(sample,group,dataset,cohort) %>% summarise(total_fibro=n(), score=mean(score_Contamination_four_gene1),.groups="drop") %>% filter(total_fibro>=50) %>% mutate(group=factor(group,levels=c("NC","PD")),dataset=factor(dataset))
dc <- model.matrix(~dataset+group,mc); fc <- eBayes(lmFit(t(as.matrix(mc$score)),dc),robust=TRUE,trend=TRUE); ttc <- topTable(fc,coef="groupPD",number=Inf,sort.by="none")
print(ttc); write.csv(mc,"G:/1Yunvjian/FigureS4_fibroblast_dataset_bias/four_gene_contamination_sample_scores.csv",row.names=FALSE); write.csv(ttc,"G:/1Yunvjian/FigureS4_fibroblast_dataset_bias/four_gene_contamination_model.csv",row.names=FALSE)
